/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.a-soltysik.Animation2D

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
