/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.a_soltysik.animation2d

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
